<?php


function taxo_menu() {
    $items['admin/myvaco'] = array(
    'title' => 'List of Taxonomy Terms',
    'description' => 'Display THe content type based on the Taxonomy.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('taxo_page'),
    'access arguments' => array('administer users'),
    'type' =>  MENU_NORMAL_ITEM,
    'file' => 'taxo.inc',
  );

 return $items;

}